url: ''
baseurl: ''
title: Three Sheets To The Wind
email: info@3sttw.nl
plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock